### ISSUE TITLE
Gitlab-collector-Index unique_mdata_key_type already exists - causing collector not to work

### ISSUE THREAD

**Issue by prabhu87** [Hygieia/hygieia-feature-gitlab-collector#3]
Facing issues with mongodb index already exists when run this hygieia-feature-gitlab-collector  API, below the error.

Caused by: com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name: unique_mdata_key_type already exists with different options' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: unique_mdata_key_type already exists with different options", "code" : 85, "codeName" : "IndexOptionsConflict" }

Could you please check this issue.

Checked out latest master branch and tested.

**Comment by prabhu87** [comment]
This issue is affected in other collectors as well, I have tried jenkins-cucumber-collector getting same error.

**Comment by rvema** [comment]
@prabhurs123 for jenkins-cucumber-collector can you create a similar issue so that it can be fixed?

**Comment by rvema** [comment]
@prabhurs123 This issue has been fixed for gitlab collector. Can you check by taking the latest code from master branch?

**Comment by rvema** [comment]
@prabhurs123 the fix was promoted to jenkins cucumber collector as well. Please retry and close this issue if this is fixed. Thanks

**Comment by prabhu87** [comment]
Thanks @rvema  it is working fine. same issue is there in hygieia-scm-gitlab-collector. I have raised the issue.Please check it and am closing this issue.
